# Generated by Django 6.0.2 on 2026-03-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('assignment_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('assignment_file', models.FileField(upload_to='assignments/')),
            ],
        ),
    ]
