# Generated by Django 6.0.2 on 2026-03-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('organization', models.CharField(max_length=200)),
                ('certificate_file', models.FileField(upload_to='certificates/')),
            ],
        ),
    ]
