# Generated by Django 6.0.2 on 2026-03-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoDueVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
