# Generated by Django 6.0.2 on 2026-03-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0007_studentprofileverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='section',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
