# Generated by Django 6.0.2 on 2026-03-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0008_assignment_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='section',
            field=models.CharField(max_length=1),
        ),
    ]
