# Generated by Django 6.0.2 on 2026-03-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0009_alter_assignment_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodueverification',
            name='hod_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nodueverification',
            name='office_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nodueverification',
            name='principal_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nodueverification',
            name='superintendent_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
